//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsConsult
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultation()
        {
            this.CounsultTypeRecord = new HashSet<CounsultTypeRecord>();
        }
    
        public int fConsultId { get; set; }
        public Nullable<int> PatinetId { get; set; }
        public string Date { get; set; }
        public string Summary { get; set; }
        public string Assessment { get; set; }
        public string Result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CounsultTypeRecord> CounsultTypeRecord { get; set; }
    }
}
